### ISSUE TITLE
Add timestamp to conversation list view

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/receiver#50]
Add a timestamp to the conversation list view. 

<img width="489" alt="Screen Shot 2022-09-15 at 11 30 14 AM" src="https://user-images.githubusercontent.com/5456408/190482237-eab5e307-59f7-4be4-b89f-3396a330ceb7.png">

**Comment by killthebuddh4** [comment]
* This was previously implemented somewhere, so we should
  1. use existing code from either the relay repo or receiver repo, I think the timestamp situation was most current in the relay repo
  2. make it look like the timestamps in the Gitcoin Demo

**Comment by killthebuddh4** [comment]
* Instead of full timestamps just use the day/date
* If it was today, say the time
* if it was yesterday, say yesterday
* if it was not today or yesterday, but within a week, say the day of the week (long format, e.g Monday)
* if it was longer than that, say the date in MM/DD/YYYY format

* if the displayed user name would push against the date, it should be truncated with "..."

**Comment by BrianS111** [comment]
There are errors in this current version which I'm addressing now and it is not ready to be merged, but should be soon. (My bad, I was looking at an old version of receiver when coding, so I wasn't actually seeing the changes being made 🤪)

**Comment by BrianS111** [comment]
These errors have been addressed and https://github.com/relaycc/receiver/pull/58 is now ready

**Comment by killthebuddh4** [comment]
Closed by #58
